### ISSUE TITLE
-Werror should be opt-in, not based on MANIFEST.in

### ISSUE THREAD

**Issue by pkubaj** [python-llfuse/python-llfuse#22]
The conditional for DEVELOPER_MODE is too widely-scoped, as source distributions (sdists) are released to end-users, and the presence of a MANIFEST.in shouldn't mean DEVELOPER_MODE.

A slightly better form might be to check for the presence of a git checkout, though this is also problematic, as users can depend on packages via their git URL's. 

The check should probably be an explicit opt-in via the presence of an environment variable DEVELOPER_MODE=yes or similar.

**Comment by ThomasWaldmann** [comment]
dirty hack, but one can now work around this by faking being on travis-ci, see ON_TRAVIS in #26.

**Comment by ThomasWaldmann** [comment]
When extracting the sdist, there is no `MANIFEST.in`. Did this change after your bug report?

I agree, this detection mechanism is a bit strange, had to hack around it (see above).

**Comment by ThomasWaldmann** [comment]
I worked a bit with the code, mainly platform and python version testing and yeah, that DEVELOPER_MODE is a pain.

Quite often it errors when compiling the code due to some issue already present in the code.

When switching off dev mode, it at least compiles.

Considering that obviously the old behaviour did not lead to fixing these issues, we can as well invert it.
