### ISSUE TITLE
fix py34 regression or drop py34 support?

### ISSUE THREAD

**Issue by ThomasWaldmann** [python-llfuse/python-llfuse#42]
since recently, tests are failing on py34:

https://travis-ci.org/github/python-llfuse/python-llfuse/jobs/745053913

**Comment by ThomasWaldmann** [comment]
looks like @Nikratio's fix (from pyfuse3) does not work on py34.

setup.py declares py34 compat for llfuse and might be used on old installations, so that would be nice to have.

otoh, if nobody fixes it, we could also drop py34 support. users running that old python can also just run an old llfuse...

**Comment by ThomasWaldmann** [comment]
maybe the issue is caused by the very old pytest version used on python 3.4.

**Comment by hugovk** [comment]
Python 3.4 has been EOL since 2019-03-18 and isn't used much.

Here's the pip installs for llfuse from PyPI for November 2020:

| category | percent | downloads |
|----------|--------:|----------:|
| 3.7      |  34.62% |       831 |
| 2.7      |  20.50% |       492 |
| null     |  12.54% |       301 |
| 3.8      |  11.00% |       264 |
| 3.6      |   9.96% |       239 |
| 3.5      |   7.92% |       190 |
| 3.9      |   3.38% |        81 |
| 3.4      |   0.08% |         2 |
| Total    |         |     2,400 |

Source: `pip install -U pypistats && pypistats python_minor llfuse --last-month`

(Python 3.5 is also EOL: 2020-09-30.)

**Comment by ThomasWaldmann** [comment]
OK, let's drop py34 support in 1.4.0 release.
